ministryofjustice/court-case-service

.circleci/config.yml
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CourtCaseEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CourtCasePropertiesEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseServiceTest.java

Replaced magic string with court lookup
Changed create case to check court correctly and throw EntityNotFoundException
Improved tests

Tech tasks

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/ApplicationExceptionHandler.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/RestClientHelper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ConvictionService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/application/ApplicationExceptionHandlerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/ConvictionControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/RestClientHelperTest.java
src/test/resources/mocks/mappings/GET_offender_convictions_404_NOT_THERE.json
src/test/resources/mocks/mappings/attendances/GET_offender_attendances_server_400_XXXXXX.json

See notes on ticket. We were getting 500 from a call to community API which yielded a 404

Pic 351 404 handling

---

.circleci/config.yml
sonar-project.properties
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/RequirementsResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiRequirementResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/KeyValue.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Requirement.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java
src/test/resources/http-request/conviction-ctrl.rest
src/test/resources/http-request/offender-ctrl.rest
src/test/resources/http-request/rest-client.env.json
src/test/resources/mocks/__files/GET_offender_requirements_X320741.json

Following discussion with Charan, added extra fields to court case service for requirements endpoint. Updates to .rest files and remove null fields from response.

pic-382 - add to requirements response

---

src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/resources/mocks/mappings/GET_offender_all_404_CRNXXX.json

pic-391 - fix intermittent test failures

---

src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiConvictionConverter.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiConvictionResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiConvictionsResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiSentence.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Sentence.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java
src/test/resources/http-request/offender-ctrl.rest
src/test/resources/mocks/__files/GET_offender_convictions_X320741.json

Court case service for termination date and reason information

Pic 384 add termination details

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/SwaggerConfig.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiConvictionResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiRequirementResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Conviction.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/FeatureFlagIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java
src/test/resources/mocks/__files/offender-convictions/GET_offender_convictions_X320741.json

Fairly small change to add single field to conviction

PIC-390 add inBreach to conviction

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/AttendanceResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiSentence.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiUnpaidWork.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Conviction.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/ProbationRecord.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Sentence.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/UnpaidWork.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/ConvictionControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java
src/test/resources/mocks/__files/offender-convictions/GET_conviction.json
src/test/resources/mocks/__files/offender-convictions/GET_offender_convictions_X320741.json

Status was needed on UPW and remove UPW from probation record call

420 add status to UPW in call to single conviction

---

.snyk

As discussed, suppress this for one month.
[https://snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-570072](url)

Pic 493 fix vuln

---

.circleci/config.yml
.snyk
build.gradle

Thanks John Evans - need to supply the policy path for suppressions to work on the docker scans

Pic 550 base image perl vuln

---

.circleci/config.yml

Ran and validated the circle jobs locally . Hopefully this will do it

:art: rename master to main

---

src/test/resources/http-request/offender-matches-ctrl.rest

Added a .rest file. It's only a test resource.

Added some requests for the grouped-offender-matches save endpoint

---

.snyk
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseServiceTest.java

SQL was wrong when deleting all cases in a day. Shown up when doing end to end tests on 624

Pic 584 delete all day

---

helm_deploy/court-case-service/templates/ingress.yaml
helm_deploy/values-preprod.yaml

Restores firewall config and removes whitelisted IP addresses
Signed-off-by: Paul Massey <paul.massey@digital.justice.gov.uk>

Tech Task: Revert changes for pentest

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/OffenderDetail.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java

✨ Added endpoint to get basic offender detail -

---

.github/dependabot.yml
build.gradle

Also reduce number of open PRs to 3

⬆️ Upgrade dependencies

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

This fix is in line with this advice from Cloud Platform regarding the ongoing ingress changes: https://mojdt.slack.com/archives/CH6D099DF/p1598458623008500
By applying these changes the existing endpoints should continue to work with no further changes

🔧 Update ingress config to match cloud platform updates

---

helm_deploy/values-preprod.yaml

🔧 Change in offender assessments URL preprod

---

.snyk
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/RequirementsResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/RequirementMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiPssRequirementResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiPssRequirementsResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/PssRequirement.java
src/main/resources/application.yml
src/test/java/uk/gov/justice/probation/courtcaseservice/BaseIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_RqmntIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/RequirementMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderServiceTest.java
src/test/resources/db/migration/development/R__seed_data.sql
src/test/resources/mocks/__files/offender-requirements/GET_pss_requirements_X320741.json
src/test/resources/mocks/mappings/offender-requirements/GET_pss_requirements_500_error_X320741.json
src/test/resources/mocks/mappings/offender-requirements/GET_pss_requirements_success_X320741.json
src/test/resources/mocks/mappings/offender-requirements/GET_requirements_500_error_X320741.json

As agreed PSS requirements is added to the existing endpoint.
Additional to the original ticket is that subtype description is also returned, but only where the maindescription is "Specified Activity". I have added that to the ticket.

✨ Added PSS requirements to the existing requirement endpoint

---

src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/AssessmentsRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/assessmentsapi/mapper/AssessmentMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/assessmentsapi/model/AssessmentsApiAssessmentsResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/assessmentsapi/model/AssessmentsApiConverter.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderService.java
src/main/resources/application.yml
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/AssessmentsRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/assessmentsapi/mapper/AssessmentMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderServiceTest.java
src/test/resources/mocks/__files/offender-assessments/GET_assessments_summary_X320741.json
src/test/resources/mocks/mappings/offender-assessments/GET_assessments_summary_404.json
src/test/resources/mocks/mappings/offender-assessments/GET_assessments_summary_500.json
src/test/resources/mocks/mappings/offender-assessments/GET_assessments_summary_success_X320741.json

There's a new URL which returns a list of offender assessments but we just have to find the latest.

✨ New offender assessment URL

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/AttendanceMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/RegistrationMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiRegistrationResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiRegistrationsResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Registration.java
src/main/resources/application.yml
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_RegistrationIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/AttendanceMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/RegistrationMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderServiceTest.java
src/test/resources/mocks/__files/offender-registrations/GET_registrations_X320741.json
src/test/resources/mocks/mappings/offender-registrations/GET_registrations_CRNXXX_404.json
src/test/resources/mocks/mappings/offender-registrations/GET_registrations_success_X320741.json

The ticket talks about "risks register" but I have stuck with the entity word "registration".

Pic 800 add registrations

---

.circleci/config.yml

💚 Fix Jira notify on deploy

---

src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/MatchType.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderMatchesControllerIntTest.java

Did not create a ticket for NAME_DOB_ALIAS

✨PIC-863 Add support for NAME_DOB_ALIAS

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

This suggests that 4 is OK for production. https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html#multiple-replicas

Increase replica count

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/BreachResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/NsiMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiNsi.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_BreachIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/NsiMapperTest.java
src/test/resources/mocks/__files/offender-interventions/GET_nsis_breach_X320741.json
src/test/resources/mocks/__files/offender-nsis/GET_nsi_X320741.json

The community API changes are deployed in dev and pre-prod and I have QA-ed locally against dev community API

Pic 830 add status date to breach

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/BreachResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/NsiMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiNsi.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_BreachIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/NsiMapperTest.java
src/test/resources/mocks/__files/offender-nsis/GET_nsi_X320741.json

Community API PR is outstanding but this can proceed safely

✨ PIC-353 Adds "notes" to the BreachResponse

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/RequirementMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiLicenceCondition.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/LicenceCondition.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/RequirementMapperTest.java

The Community API updates are deployed to dev / test / preprod

✨ PIC-914 add to LicenceCondition

---

src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/RegistrationMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/BreachMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderServiceTest.java
src/test/resources/mocks/__files/offender-interventions/GET_nsis_breach_X320741.json

Applied Nested to OffenderServiceTest. It brings all the tests against the same methods together. Simplifies things if you are looking at an area which is not getProbationRecord.

✨ PIC-916 sort breaches by status date desc

---

helm_deploy/court-case-service/templates/deployment.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

💚 Increase maxSurge k8s configuration to prevent prod deployment timeouts

---

helm_deploy/court-case-service/templates/deployment.yaml
helm_deploy/court-case-service/templates/hpa.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Followed example at 
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html#horizontal-pod-autoscaling
Set maxReplicaCount to 8 for pre-prod and prod, based on performance tests so far

Pic 871 auto scale

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/InterceptorConfigurer.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/UpperCasePathVariable.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/UpperCaseResolver.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/UpperCaseResolverTest.java

Having problems with CRNs with spaces and lowercase - replace PathVariable for CRN which can transform

🐛 PIC-1118 handle CRN as PathVariable

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtControllerIntTest.java
src/test/resources/before-test.sql

I've had to approach this in a slightly weird way due to being unable to run the tests locally without my normal laptop but I've seen the test fail in CI and subsequently pass so I'm confident they're doing what they should.  I've done the most basic implementation and test I can given the difficulties I've got in making significant changes at the moment, happy to follow up with improvements when I'm back to my normal set up but would be good to merge asap to get PAC back in working order.

✨ PIC-1157: Always return manual updates for court-cases

---

src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiProbationStatusDetail.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java
src/test/resources/mocks/mappings/offender-probationStatus/GET_probation_status_success_X320741.json

fix mapping object,  "status" coming from community API but we expect "probationStatus"

🐞 PIC-1165 fix mapping objects  "status" coming from community 

---

src/main/resources/application.yml

Pic 1348 open in view

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/GroupedOffenderMatchRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderMatchService.java
src/main/resources/application-local.yml
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderMatchServiceTest.java

Each fetch for the count of matches was 2 SQL statements. This reduces it to 1

🚀 PIC-1348 reduce SQL statements to get offender match count

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/resources/before-test.sql

Constrain default case list query to cases created 8 days before hearing date

⚡️ PIC-1355: Constrain default case list query

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java

✨ PIC-1457 return 304 if page is unmodified

---

helm_deploy/values-dev.yaml

Signed-off-by: katie-cawthorne <katie.cawthorne@digital.justice.gov.uk>

:wrench: PIC-1515: apply cpu and memory limits for dev

---

src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiOffence.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Offence.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java

Adds "main" boolean to offence and date

PIC-1526 add fields to offence

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ConvictionService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_ConvictionIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ConvictionServiceTest.java

- Added new sentence endpoint but left redundant endpoint until PIC-1534 has been completed. Ticket PIC-1566 has been created to remove the endpoint following PIC-1534.
- Updated tests, added tests for new endpoint.
Signed-off-by: katie-cawthorne <katie.cawthorne@digital.justice.gov.uk>

:sparkles: PIC-1533: Add duplicate sentence endpoint

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_ConvictionIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClientIntTest.java

🔥  removed redundant sentence endpoint
✅  removed and amended tests
Signed-off-by: katie-cawthorne <katie.cawthorne@digital.justice.gov.uk>

:fire: PIC-1566: remove redundant sentence endpoint

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseServiceTest.java

Ticket refers to not returning the caseNo field which explains a fair amount of the change.

✨ PIC-1608 get case by case ID

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/CourtCaseResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/HearingResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseServiceTest.java
src/test/resources/before-test.sql

Now using hearing collection to set court room / court code etc in the `CourtCaseResponse`. Also added a `hearingDays` array to `CourtCaseResponse`.

✅ PIC-1665 PR comments - improve handling of multiple cases

---

build.gradle

Looks like our dev deployment failures started with this

🔖 rollback junit bom

---

src/main/resources/db/migration/courtcase/V2005__add_defendant_uuid.sql

I broke the build, brain not functioning at 100% this week I think 😅

💚  Revert breaking change to migration

---

.snyk

One line change ! We need to review which base image we use here

🔐 Extend vulnerability suppression

---

src/main/kotlin/uk/gov/justice/probation/courtcaseservice/CourtCaseServiceApplication.kt

🗃 PIC-1651: Enable retry

---

src/main/resources/db/migration/courtcase/V2121__remove_historic_common_platform_duplicates.sql

https://dsdmoj.atlassian.net/browse/PIC-2128

🔥 PIC-2128: Add migration to clear out historical records

---

src/main/java/uk/gov/justice/probation/courtcaseservice/service/UserAgnosticOffenderService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/UserAgnosticOffenderServiceTest.java

. Added null check on the isBreach and awaitingPsr fields.

.PIC-2410-fix

---

.circleci/config.yml

Also allow scheduled workflow to be run on all branches containing 'workflow_test_branch'

🛠 PIC-2679: Add hmpps-common-vars to scheduled workflow

---

hooks/pre-commit
hooks/pre-push

Also only run unit and integration tests if the src/ folder has actually changed.
Once this is merged you'll need to pull main and run `./gradlew installGitHooks` to apply the changes to your machine.

🪝 PIC-1667: Check circle config is valid on commit if it has changed

---

src/main/resources/db/migration/courtcase/V2140__unique_constraints_on_hearing_and_defendant_ids.sql

This has now been tested against prod data in preprod and the migration applied without incident. This can be deployed asap after the Xmas change freeze.

🐛 PIC-2613: Fix migration

---

helm_deploy/court-case-service/templates/ingress.yaml

Fix issue with incorrectly attempting to apply configuration for specific path to all paths 
Introduced by commit 60b191d

🐛 PIC-2476: Fix nginx misconfiguration

---

.circleci/config.yml
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorService.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorServiceTest.kt

- Strip punctuation characters from Court name for short term custody algorithm
- Circle CI fix

PIC-2655 Court name fixes

---

Dockerfile
build.gradle
src/main/resources/application.yml
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerPutByHearingIdIntTest.java
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorServiceTest.kt

- New version of Data Science Short Term Custody Algorithm
- Bump up Spring Boot to 2.7.9

PIC-2655 Incorporate new Data Science algorithm JAR

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/security/OAuth2SecurityConfig.java

- upgrade to latest Spring 2.7.xx version
- upgrade to Spring Security 5.8
- initial refactor to prepare for Spring Security 6.0

Pic 3361 initial security refactor

---

src/main/java/uk/gov/justice/probation/courtcaseservice/security/OAuth2SecurityConfig.java
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/health/HealthInfo.kt
src/main/resources/application.yml

- Tweaked security config request matcher for health endpoint URL
- Updated application.yaml endpoint config for health endpoint
- Added custom HealthIndicator

PIC-3361 Add HeathIndicator implementation

---

helm_deploy/court-case-service/templates/data-dictionary-service.yaml
helm_deploy/court-case-service/templates/nginx-service.yaml
helm_deploy/values-dev.yaml

undo the nginx port number changes

Rollback data-dictionary deployment fix

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Update helm values for prod and preprod to include the Oxford court code

PIC-3813: Send all un-outcomed cases to Outcomes Workflow for Oxford Magistrates Court

---

src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/CaseWorkflowService.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/CaseWorkflowServiceTest.kt

- Remove duplicates of assigned users and courtrooms in v2 hearing-defendant-outcomes response
- Add tests

PIC-3808 Remove duplicates from assigned users and courtrooms

---

src/main/resources/application-dev.yml

Add the PREPARE_A_CASE role to the hmpps SAR endpoint for DEV
This is so that we can do testing in dev.

PIC-3848 Allow PREPARE_A_CASE role to access SAR endpoint

---

src/main/resources/application-dev.yml

Add quotes to enable the PREPARE_A_CASE role

PIC-3848 Add quotes to enable the PREPARE_A_CASE role 

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingRepositoryFacade.java

Add the interpolation into the logging string.

PIC-4138 Fix logging implementation

---

src/main/resources/application-local.yml

Place datasource and flyway config under the spring config in applicaiton.local
```
spring:
datasource: ...
flyway: ...
```
otherwise it will use the datasource in `application.yml` which has `sslmode=verify-full` in the url
which causes an exception during server startup of `PSQLException: The server does not support SSL.`

Fix local setup

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingRepositoryFacade.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/HearingEntityInitService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/HearingNotesService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
src/main/resources/db/migration/courtcase/V2183__drop_hearing_id_constraint.sql
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingRepositoryFacadeIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/HearingNotesServiceTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseServiceTest.java

PIC-4279: Changes to cater for when hearings can have multiple cases associated with the same hearing id

PIC-4279: Changes to cater for when hearings can have multiple cases

---

.circleci/config.yml

As far as I can tell the built data dictionary image is not used for anything.
There is a stack of associated code to clean up.  [A ticket for that work](https://dsdmoj.atlassian.net/browse/PIC-4392)

CPR-4372 remove non-working data dictionary job

---

src/main/resources/db/migration/courtcase/V2188__add_court_case_id_to_hearing_aud.sql

Add court_case_id to hearing audit table after adding the new column in the hearing table
https://github.com/ministryofjustice/court-case-service/pull/1310

PIC-4372 Add court_case_id to hearing audit table

---

src/main/java/uk/gov/justice/probation/courtcaseservice/service/HearingEntityInitService.java
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingOutcomeRepositoryCustom.kt
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerPutByHearingIdIntTest.java

Ensure deleted hearing outcomes are filtered out before returning data from the api

PIC-4373: Ensure deleted hearing outcomes are filtered out.

---

src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/HearingOutcomeType.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/controller/CaseWorkflowControllerIntTest.kt

Add Fine and Dismissed as new outcome types.

Pic 4358 new outcome types

---

build.gradle

Upgrade to Kotlin Version 2

---

build.gradle
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/config/OpenAPIConfiguration.kt

Reverts ministryofjustice/court-case-service#1221

Revert "Update dependency uk.gov.justice.service.hmpps:hmpps-kotlin-spring-boot-starter to v1"

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CaseDefendantEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/HearingEntityInitService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapperTest.java

Remove lazy loading of case documents due to it sometimes failing when consuming libra messages from court-case-matcher

PIC-4518 remove lazy loading

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Append /auth to the nomis auth url ... after work done on the Pinger class

BugFix nomis auth url append /auth

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/healthchecks/Pinger.java

Fix Ping calls to api dependencies

---

helm_deploy/court-case-service/templates/_envs.tpl

This is a fix forward for https://github.com/ministryofjustice/court-case-service/pull/1350
Update the helm template k8s secret referencing

PIC-4103 fix helm secret referencing

---

build.gradle
src/test/java/uk/gov/justice/probation/courtcaseservice/BaseIntTest.kt
src/test/resources/application-test.yml

This should fix this CVE for us https://spring.io/security/cve-2025-22233
This should also fix our other CVE

PIC-4650 update to 8.2.0 that fixes cves too

---

src/main/java/uk/gov/justice/probation/courtcaseservice/service/DomainEventService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderUpdateService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/event/DomainEventType.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/DomainEventServiceTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderUpdateServiceTest.java

Emit event to the hmpps doamin events topic for link/unlink ndelius offender

PIC-4726: Emit event to the hmpps doamin events topic for link/unlink ndelius offender
