ministryofjustice/court-case-service

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/PingEndpoint.java

Allows Cross-origin resource sharingCross-origin resource sharing on /ping endpoint so that healthcheck can be hit from Frontend code (such as build radiator)

CORS support

---

build.gradle
src/test/java/uk/gov/justice/probation/courtcaseservice/RetryService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/TestConfig.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/resources/mocks/mappings/wiremock-readiness.json

We looked to be hitting the exact same issue described here 
[https://github.com/tomakehurst/wiremock/issues/1224](url)
This ticket reports this 
> we sometimes have failures once Spring launches a fresh context and Spring Security tries to get OAuth2 token (this call is stubbed within WireMock server)
The workaround was to do this
> We now have a workaround and add a simple e.g. /readiness/wiremock stub right after starting the WireMockServer and try to hit it with a simple retry-mechanism and once HTTP status 200 returns we continue we our setup.
The ticket was closed with no fix. So this commit does the same thing as described

Awaiting Wiremock to be ready. 

---

docker-compose.yml

As per the community-api-pr channel, docker image has moved

Update community API docker URL

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/BreachResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/DocumentRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/DocumentMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/NsiMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/model/CommunityApiOffenderDocumentDetail.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/BreachService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/document/OffenderDocumentDetail.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/DocumentMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/NsiMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/OffenderMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/BreachServiceTest.java
src/test/resources/http-request/rest-client.env.json
src/test/resources/mocks/__files/offender-documents/GET_documents_success_X320741.json

Note the ticket refers to endpoint at 
`/offender/{crn}/breaches/{breachId}`
But existing BreachResponse was served up from below conviction, here 
`offender/{crn}/convictions/{convictionId}/breaches/{breachId}`
Assuming it was the latter. If it's the former then it's easy enough to add that.

400 - include breach documents in BreachResponse

---

helm_deploy/court-case-service/templates/ingress.yaml

See PIC-437 for details of why this change is needed, this is not a perfect but debugging the precise cause has proved impossible so far so will disable for now to get it working again and raise another ticket to do further investigation as and when it becomes priority.

☸️  PIC-437: Disable ModSecurity rule

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/CourtCaseResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/AddressPropertiesEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CourtCaseEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/main/resources/db/migration/courtcase/V108__make_unique_key_for_court_and_case_no_court_case.sql
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerPutIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseServiceTest.java
src/test/resources/http-request/court-case-ctrl.rest
src/test/resources/http-request/rest-client.env.json
src/test/resources/integration/request/PUT_courtCase_success.json

The PUT to create / update by case ID is deprecated. We now update by what we are thinking of as our unique business key (court code and case no). The headline of this change is a new method that does pretty much the same as the PUT by case ID. Other associated changes
- make a unique key of court code / case no. These fields should be immutable once saved so no setters on the Entity object
- case no is no longer unique by itself

:sparkles:  518 PUT by court and case no

---

.snyk
helm_deploy/values-prod.yaml

Fixing the issue with the helm release corruption brought to light another failure in waiting due to a missing property which this commit fixes

💚 Add missing prod value

---

.snyk

We are suppressing again - the hibernate dependency causing the problem is part of spring data and we've previously decided not to pick apart those dependencies.
The perl dates have been pushed forward. Will raise an item for discussion on Monday stand up and whether we want to go to Alpine / JDK 11

Fix vulnerability 

---

src/test/java/uk/gov/justice/probation/courtcaseservice/BaseIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/RetryService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerPutIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_ConvictionIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderMatchesControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/PingControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/health/HealthCheckIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/AssessmentsRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/DocumentRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/NsiRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/OffenderRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseServiceIntTest.java

As a bit of background,  at startup, Spring Security now makes a request to the auth server for a public key to verify with. In our integration tests I've introduced a mock to make sure it doesn't fall over at this point - as we know though, wiremock can be a bit slow to start up and if the auth mocks aren't there then application will completely fail to start. 
The retry mechanism that we introduced was operating at the instance level in the @Before method, but because of the auth changes this is now too late - the first request will already have been made on application startup. To address this I've now moved that retry to @BeforeClass and made it static to allow this.
While I was in there I also extracted a BaseIntTest class which has removed a big chunk of boilerplate 🔥

Fix flaky tests

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerPutIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ConvictionServiceTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseServiceIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseServiceTest.java
src/test/resources/application-test.yml
src/test/resources/before-test.sql
src/test/resources/http-request/court-case-ctrl.rest

The code takes a list of case numbers for a date / court code and deletes any cases found for that court / date which are not n the list of case numbers. The list of case numbers has arrived and is the full list of cases for that date / court.
The approach is to use SQL to get a list of cases to delete and then use a standard Spring-provided repository delete method to delete them. Due to work done earlier, this is a "soft delete" and cascades to child offences. Other approaches were looked at 
- Custom query to to a DELETE. Unfortunately it's a feature of JPA that this doesn't cascade to child entities and doesn't understand the soft delete. SO we'd have had to write it as an UPDATE on both the COURT_CASE and OFFENCE tables.
- CriteriaBuilder - again this would have to be written as an …

✨ Allow missing cases for a date to be deleted

---

src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Conviction.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/ConvictionBySentenceComparator.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderServiceTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/model/ConvictionBySentenceComparatorTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/model/ConvictionTest.java
src/test/resources/mocks/__files/offender-convictions/GET_offender_convictions_X320741.json

The existing sort order needs to handle active and non-active differently

🐛 Refine sort order for convictions

---

.circleci/config.yml

See [ticket](https://dsdmoj.atlassian.net/browse/PIC-826) for proof it's working.
Note that it isn't clever enough to distinguish between different jobs in a build - as far as Jira is concerned it's either built or it isn't. Because of this I'm reporting only on build and docker-build which are sequential so we won't get a situation where a parallel job succeeds and overrides a previously reported and valid failure status. If the app scan fails we won't see it in Jira but this seems to just be a limitation of the integration.

👷‍♂️ PIC-826: Enable CircleCI Jira integration

---

src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/OffenderDetail.java
src/main/resources/application.yml
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_BreachIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClientIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/NsiRestClientIntTest.java
src/test/resources/mocks/mappings/attendances/GET_offender_attendances_server_404_X320999.json
src/test/resources/mocks/mappings/offender-appearances/GET_appearances_success_X320741.json
src/test/resources/mocks/mappings/offender-nsis/GET_nsi_404_CRNXXX.json
src/test/resources/mocks/mappings/offender-nsis/GET_nsi_404_X320741_unknown_breach_id.json
src/test/resources/mocks/mappings/offender-nsis/GET_nsi_server_error_X320741.json

The problem was an incorrect path (in application YML and wiremock tests) for the court appearances so I have fixed this. There are also now 4 integration tests instead of the 2 we had before.

👌🏻 PIC-442 Fix path for court appearances within the breach endpoint

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/WebClientConfig.java
src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/DocumentRestClient.java
src/main/resources/application.yml

The document is streamed and you need to give spring / reactor a buffer size in the decoder. By default this is 262144 as given in AbstractDataBufferDecoder. So as to not change the value in other webclients, added a specific new one for the documents. Others will continue to work with the same values.

Pic 909 file size download

---

helm_deploy/court-case-service/templates/ingress.yaml

This is a temporary removal as this method is no longer supported by Cloud Platform. Have raised [PIC-1018](https://dsdmoj.atlassian.net/browse/PIC-1018) to reintroduce once the migration has been completed

💚 PIC-1017: Remove modsecurity snippet from ingress

---

helm_deploy/court-case-service/templates/hpa.yaml

The HPA uses requests instead of limits for its calculation. Our pods have already been reserved 10m so that is guaranteed resource. We should only scale if it gets to 100% - this will allow for better down-scaling.
Done some tests now - on dev
```
Normal  SuccessfulRescale  43m                  horizontal-pod-autoscaler  New size: 4; reason: All metrics below target
Normal  SuccessfulRescale  40m                  horizontal-pod-autoscaler  New size: 3; reason: All metrics below target
Normal  SuccessfulRescale  39m                  horizontal-pod-autoscaler  New size: 6; reason: cpu resource utilization (percentage of request) above target
Normal  SuccessfulRescale  30m (x2 over 57m)    horizontal-pod-autoscaler  New size: 7; reason: All metrics below target
Normal  SuccessfulRescale …
```

🔧 PIC-871 change targetCPUUtilizationPercentage following guidance

---

src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClient.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/CustodialStatus.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/ConvictionRestClientIntTest.java
src/test/resources/mocks/__files/offender-currentOrderHeaderDetail/GET_currentOrderHeaderDetail_NotInCustody_E396405.json
src/test/resources/mocks/mappings/offender-custodialStatus/GET_custodialStatus_success_E396405.json

The incoming code was NOT_IN_CUSTODY which was not in our enum. I have added this but the new test is based on a code which is also not in the enum. No longer a null pointer.

✨ PIC-1144 when CustodialStatus code is unknown - fix NPE

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/CourtCaseResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CourtCaseEntity.java
src/main/resources/db/migration/courtcase/V1122__alter_probation_status.sql
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/model/CourtCaseResponseTest.java
src/test/resources/before-test.sql

The CourtCaseResponse has a string for probation status and it has a getter method to determine if it is null / unmatched then can return "Possible nDelius record". So we don't store that value in the database anymore. PROBATION_STATUS can be null in these cases. Also is some migration. 
Fixed integration tests.

✨ allow probation status to be null and handle "Possible nDelius record"

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/DeploymentLogger.java
src/test/java/uk/gov/justice/probation/courtcaseservice/DeploymentLoggerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/TestAppender.java
src/test/resources/logback-test.xml

Not particularly happy with this as a solution but it works. Spring ought to log the version automatically from what I can tell but for reasons I don't understand it isn't. In the end I've taken the pragmatic approach and just logged it again as I managed to do that in less time than it took me debugging why it wasn't working in the first place 🙄

📈 PIC-1270: Log deployment message with version on application start

---

.circleci/config.yml
build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/security/OAuth2SecurityConfig.java
src/test/java/uk/gov/justice/probation/courtcaseservice/application/UnsecuredResourceServerConfiguration.java
src/test/java/uk/gov/justice/probation/courtcaseservice/pact/CourtCaseMatcherVerificationPactTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/pact/PrepareACaseConsumerVerificationPactTest.java

Verifies and publishes PACT results to the broker. Only prepare-a-case at the moment. court-case-matcher PACTS are not being verified. We may need separate state verification provider classes. 
@jhevans - this doesn't line up 100% with the user-preferences implementation. It does not mix the 4.2.x dependencies with this one. Maybe we should review jointly.
`testImplementation("au.com.dius:pact-jvm-provider-junit5:4.0.10")`

Pic 959 contract provider

---

README.md
doc/adr/0004-nginx-caching.md
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java

When going through the ADR it occurred to me that we can do better than just logging "now" as the last modified date and allow the client to cache if they want. As long as we consistently keep returning an arbitrary date in the past then it will be guaranteed to update as soon as a new update comes through (because the timestamp will be in the present not the past).
The date I chose is pretty arbitrary but I went for a nice round 2020-01-01 - so before we started getting real data but around the inception of the court-case-service as a thing.

✏️ PIC-1406: Update ADR and use default case list Last-Modified date

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/CustodyDetail.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/SentenceResponse.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ConvictionService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderController_ConvictionIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ConvictionServiceTest.java

Approach is to duplicate the fields, prepare a case can move to the new ones and then we can remove the old `currentOrderHeaderDetail` which is now deprecated

🔨 PIC-1529 refactor getSentence

---

src/main/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/DocumentMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/Conviction.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/model/document/OffenderDocumentDetail.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/restclient/communityapi/mapper/DocumentMapperTest.java

Adds "`psr`" boolean to the documents. The `psrReports` array remains in place but should now be ignored. Subsequent tickets will be raised for prepare a case to use the new boolean and to remove psrReports

🐞PIC-1574 boolean to mark document as a PSR one

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CourtCaseEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CourtSession.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/DefendantEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/DefendantOffenceEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/HearingEntity.java
src/main/resources/db/migration/courtcase/V2000__add_hearing_defendant_newoffence_table.sql
src/test/resources/before-test.sql

Have also added some sample data. I tested the fetching of linked collections by debugging existing tests but didn't want to add methods to our services which would enable full integration tests.
As mentioned in a comment, the CourtCaseEntity cannot have 3 collections annotated with EAGER. We will need to look at this when we start fetching in our services but it looks like the Hibernate annotation LazyCollection could be a solution. We may need to start considering what should be lazy or not, and adjusting the session boundaries.
I haven't done it here but I think we should probably adopt a hearingDay field in the HEARING entity because we usually search on the hearing date (with no time) and it would give a more performant query.

✨ PIC-1581 add new JPA entities

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseServiceTest.java
src/test/resources/before-test.sql

SQL to check for existing case doesn't need the subqueries to discover the firstCreated date. Just need an existing case. The only details ae used in logging.

✨ PIC-1618 alter save of case by case no

---

src/main/resources/db/migration/courtcase/V2002__remove_breaking_not_null.sql

After some checking (see comments on ticket), looks like these are the only problematic fields. Some fields like list_no and court_room are nullable in court_case but have never been null in the life of our system so we'll leave those not null.

🐞 PIC-1626 remove not null constraints

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseCaseIdController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
src/main/resources/db/migration/courtcase/V2004__add_fk_hearing_court.sql
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/resources/before-test.sql

The  intent of the ticket was to remove the FK relationship from court_case to court and add it to court_case to hearing. This is done in the ticket. Also changed was the queries related to the endpoint /court/{court}/cases. As discussed, so as to enable more easy performance testing later, I have added new queries and a new controller at a new endpoint at /court/{court}/cases/extended. There is a new @Nested set of test classes in the CourtCaseControllerIntTest for this new endpoint. These test cases are exactly the same as the ones for the old get cases endpoint, save for the path.
The biggest part of the work was refactoring and adjustment of the before-test.sql. I had to add hearing records for most of the cases, as well as controlling the (usually generated) id fields for court_case. …

🐞 PIC-1609 create new endpoint controller for getCases (extended)

---

src/main/resources/db/migration/courtcase/V2007__archive_old_records.sql

Clear out everything before 1 June 2021. Copy same records to tables with `_archive` extension. 
We have to treat `offender_match` and `offender_match_group` differently because there is no FK relationship from `offender_match_group` to `court_case` and these tables do not have immutable records so we can't just delete based on a date. Need to delete parent records from `court_case` and then delete orphans from `offender_match` based on case no and court code.
I have put the SQL In a script to be executed by flyway. We could arguably do this manually with more control, and checking as we go. Happy to reconsider the approach.

🔧 PIC-1642 clear out older records

---

.snyk
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderMatchesController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/GroupedOffenderMatchesEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/GroupedOffenderMatchRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderMatchService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/mapper/OffenderMatchMapper.java
src/main/resources/db/migration/courtcase/V2008__offender_match_defendant_and_case_id.sql
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderMatchesControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/OffenderMatchesControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderMatchServiceTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/mapper/OffenderMatchMapperTest.java
src/test/resources/before-test.sql

1. Allows for the saving of offender matches by case and defendant ID.
2. Adds case_id and defendant_id to the offender_match_group table, makes a compound index of these 2 fields and that is unique.
3. Migrates existing case and defendant IDs. There is a known issue whereby some latest case versions do not have defendant IDs. It has been  decided on slack that we will work around that in subsequent tickets for match detail and match counts by falling back to looking up defendant id from court code and case no
4. We will investigate further the source of the issue of missing defendant IDs

✨ PIC-1619 - save offender match group by defendant and case id

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/CourtCaseEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/DefendantEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/HearingEntity.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CourtCaseService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/mapper/CourtCaseMapper.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerPutIntTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapperTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/EntityHelper.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseServiceTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/mapper/CourtCaseMapperTest.java
src/test/resources/before-test.sql
src/test/resources/integration/request/PUT_courtCase_success.json

Also part of this change is the fix whereby the update on probation status for other future cases for the same CRN was not saving hearings, defendants and defendant offences.
Removed the custom equals and hashCode implementations on CourtCaseEntity.

✨ PIC-1720 - add save by case and defendant id

---

src/main/resources/db/migration/courtcase/R1__update_offender_match_group_apply_ids.sql

This is the same SQL which has already been applied last time we did a flyway migration, except that 
- it constrains to leave records in `offender_match_group` which already have case and defendant id set
- it sets a `last_updated` timestamp
- it sets a `last_updated_by` value (migration)
I ran it in pre-prod just now

✨ PIC-1753 - repeatable migration for offender_match_group

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/Defendant.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/model/DefendantTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/model/ExtendedCourtCaseRequestResponseTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/SexTest.java

Only line of prod code is to remove an annotation, allowing defendant sex to be null (can happen from LIBRA), the rest is tests to cover

✨ PIC-1859 defendant sex may be null when received

---

src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderMatchService.java

Having examined the code I'm pretty sure I can see where the issues are arising and it seems that we need a slightly higher level of isolation than the default (`Isolation.READ_COMMITTED`) to achieve this. Here's the documentation for `Isolation.REPEATABLE_READ` as its non-obvious. The issue I believe we're seeing is in bold italics:
> A constant indicating that dirty reads and non-repeatable reads are prevented; phantom reads can occur. This level prohibits a transaction from reading a row with uncommitted changes in it, and **_it also prohibits the situation where one transaction reads a row, a second transaction alters the row, and the first transaction rereads the row, getting different values the second time_** (a "non-repeatable read").

🗃 PIC-1615: Prevent optimistic locking failures for concurrent updates

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/ApplicationRetryListener.kt
src/test/java/uk/gov/justice/probation/courtcaseservice/application/ApplicationRetryListenerTest.kt

close method is also called on success so current message is misleading

🔉 PIC-1946: Correct log message

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CourtCaseRepository.java

This reverts commit de70cf150b487cb4a7f62fa0ec4ba6376cb32938.

Revert "🐛 PIC-1958: Fix SQL prematurely filtering on court code"

---

.circleci/config.yml
Dockerfile

The snyk scan on docker_build is blocking merges of new features and disrupting our workflow. As this scan is performed on a scheduled basis on main anyway this doesn't provide much additional value so deleting.

🔥 PIC-2117: Remove redundant Snyk scan on docker build

---

src/main/resources/db/migration/courtcase/V2131__set_unique_personid_per_defendantid.sql

This reverts commit 90520e10fc7c67960acac519e40425de584610cf which is no longer needed and has been causing problems when migrating the Prod DB. I've run flywayRepair on the dev and preprod Flyway migrations so that this will deploy.

Revert "PIC-2563 (#964)"

---

src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorService.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorServiceTest.kt

* Ensure ShortTermCustodyPredictorScoreService does not throw exception on failure
* Only attempt to update score on offence if algorithm successfully runs

PIC-2655 Short term custody service fixes

---

build.gradle
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorService.kt
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerPutByHearingIdIntTest.java
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorServiceIntTest.kt

- Data science have detected that the incorrect score (P0) is being returned from the algorithm
- Fix to return P1 score instead

PIC-2655 Ensure Short Term Custody algorithm returns P1 score

---

build.gradle
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

We've increased k8s pod resources in the past, but didn't up the Java heap size accordingly.
I've increased both the heap size and the k8s resources size to realistic values for production spring boot services.

PIC-3280 Increase Java heap size

---

helm_deploy/values-dev.yaml

This is because prepare a case service is getting a 413 http response
"client intended to send too large body: 6156882 bytes" as it tries to upload a 6mb file.
The Cloud Platform Kibana Ingress Logs suggest it's due to the `court-case-service-proxy` ingress server defaulting to a max of 1megabyte
**Additional information:**
https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size

Increase the Nginx/ingress body size limit for requests for DEV

---

helm_deploy/court-case-service/templates/ingress.yaml
helm_deploy/values-dev.yaml
nginx/nginx.conf

Increase the file upload size limit to 50M by updating the nginx.conf file `client_max_body_size` value and also updating the ingress.yaml
This is to allow a large file upload from prepare-a-case service. The default nginx limit is 1mb which isn't enough.
Undo this previous PR as we have an nginx.conf file available: https://github.com/ministryofjustice/court-case-service/pull/1182

Increase client_max_body_size in nginx/ingress

---

build.gradle
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CaseSearchController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/CourtCaseServiceApplication.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/config/OpenAPIConfiguration.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/CaseWorkflowController.kt

- Remove the `org.springdoc:springdoc-openapi-ui:1.7.0` that only supports springboot 1 and 2
- Add `springdoc-openapi-starter-webmvc-ui` that supports Spring Boot 3
This fixes the endpoint `/swagger-ui.html`
Allowing users to read and use the api documentation
- Fix one of the endpoints documentation as it was using an Object for the query param so it needs to use the `@ParameterObject`
- Implement OAuth2 Bearer Token with Swagger Document
- I believe that in order to get the token for preprod/prod, you'll need to use the auth code grant flow. For Dev, you can use the client credentials found in its k8s secrets.

Fix Swagger OpenAPI documentation

---

build.gradle

Upgrade o`rg.postgresql:postgresql` to `42.6.1
`This fixes a critical security vulnerability https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-6252740
Preventing SQL Injections.

Fix Critical Security Vulnerability found by SNYK

---

helm_deploy/court-case-service/templates/data-dictionary-deployment.yaml

Allow the k8s data-dictionary deployment to bind to the k8s service
why?
Alpinelinux uses User 101 hence why we have runAsUser: 101. This does not currently have the permissions to bind to port 80 (which is where the ingress is running on)
Fixes the error:
`nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)`

Deployment Fix: Resolve permission issues for data-dictionary deployment

---

helm_deploy/court-case-service/templates/data-dictionary-deployment.yaml

adding the port binding capability to user 101, it should be under the `capabilities` property

Fix data dictionary kubernetes config format

---

helm_deploy/court-case-service/templates/data-dictionary-service.yaml
helm_deploy/court-case-service/templates/nginx-service.yaml

This should fix the deployment issue for data dictionary:
`Error: UPGRADE FAILED: cannot patch [data dictionary service] with kind Service: Service  [data dictionary service]  is invalid: spec.ports[1].name: Duplicate value: "http"`

Deployment Fix: Change data-dictionary service port name to be unique

---

src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/ShortTermCustodyPredictorService.kt

In response to an issue causing an influx of error messages in our logs, this PR addresses the uncaught exception scenario within `ShortTermCustodyPredictorService.kt`. Previously, unhandled exceptions were leading to a cluttered error log, hindering our ability to effectively monitor and troubleshoot issues.
This PR aligns with our ongoing efforts to enhance the stability and performance of our services, contributing to a more robust and reliable infrastructure.

PIC-3822: Catch "hex.genmodel.easy.exception.PredictUnknownCategoricalLevelException" correctly

---

src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/CaseWorkflowController.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/HearingOutcomeCaseList.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/filters/FilterItem.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/filters/FilteredOutcomesResponse.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/filters/FilteredResourcesResponse.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/filters/FiltersList.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/filters/HearingOutcomeStatesFilterItem.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/v2/HearingDefendantOutcomesRequest.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/v2/HearingOutcomeCaseList.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/controller/model/v2/HearingOutcomeCountByState.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/jpa/entity/HearingOutcomeAssignedUser.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingOutcomeRepositoryCustom.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/CaseWorkflowService.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/HearingOutcomeType.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/PaginatedHeadersService.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/v2/FilterHearingDefendantOutcomesService.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/controller/CaseWorkflowControllerTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/controller/v2/CaseWorkflowControllerIntTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingOutcomeRepositoryCustomIntTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingOutcomeRepositoryCustomPaginationIntTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/CaseWorkflowServiceIntTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/CaseWorkflowServiceTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/PaginatedHeadersServiceTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/v2/FilterHearingDefendantOutcomesServiceTest.kt
src/test/resources/sql/hearing-outcomes-unresulted-cases.sql

**Tickets**:
[V2 endpoint](https://dsdmoj.atlassian.net/browse/PIC-3808)
[Bug fix assigned uesrs](https://dsdmoj.atlassian.net/browse/PIC-3725)
**Bug Fix:**
The user requirements did not want assigned users to be paginated
- Return all `assignedUsers` property for GET `/courts/{courtcode}/hearing-outcomes` which has all the assigned users on hearing-outcomes with no pagination
- do the same for the v2 endpoint
**Change Pagination:**
- Remove pagination from `HearingOutcomeRepositoryCustom.findByCourtCodeAndHearingOutcome` and return all the filtered results
- Get all assigned users without pagination.
- This came after removing pagination from `hearingOutcomeRepositoryCustom.findByCourtCodeAndHearingOutcome`
- Return assignedUsers in `HearingOutcomeCaseList` for function …

PIC-3725 and PIC-3808 Return all Assigned Users for court & Create V2 endpoint

---

build.gradle

Upgrade application insights version to version `3.5.2`
hoping to fix the error:
`ERROR c.m.applicationinsights.agent - Application Insights Java Agent 3.4.9 startup failed (PID 1)`

PIC-3848 Upgrade application insights version

---

helm_deploy/values-dev.yaml
src/main/resources/application-dev.yml

Add `PREPARE_A_CASE` role to `hmpps.sar.additionalAccessRole` environment property
This allows us to test the SAR endpoint with our token that has role `PREPARE_A_CASE`

PIC-3848 Allow SAR endpoint testing in dev

---

Dockerfile

Allows our service to trust the [updated certificates](https://github.com/ministryofjustice/cloud-platform-environments/pull/24022) from our RDS database in cloud platform

Add AWS RDS CA-Cert bundle into Dockerfile

---

src/main/resources/db/migration/courtcase/V2179__add_defendant_name_index.sql

Add an index to find a defendant by PNC, forename1 and surname
We have an SQL taking up a lot of CPU and making many calls:
```
select * from defendant where pnc= $1 and date_of_birth = $2 and lower(name->>?) = lower($3) and lower(name->>?) = lower($4)
```
This index should hopefully reduce the average speed and CPU usage

PIC-3939 Add index on defendant names

---

src/main/kotlin/uk/gov/justice/probation/courtcaseservice/client/model/listeners/SQSMessage.kt
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/listeners/OffenderDomainEventListener.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/listeners/OffenderDomainEventListenerIntTest.kt
src/test/kotlin/uk/gov/justice/probation/courtcaseservice/service/listeners/OffenderDomainEventListenerTest.kt

Set a threshold of 2 days
Do not process messages that are older than 2 days for the `picnewoffendereventsqueue`. As it has already been processed.
This should reduce the number of queries made to our database and therefore improve performance.

PIC-4018 Set timestamp threshold for processing messages

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/CaseCommentsRepository.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/CaseCommentsService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/CaseCommentsServiceTest.java

Due to a data race, more than 1 draft comments can be saved in the database which shouldn't happen.
This leads to users unable to save a comment, which is caused by the below `NonUniqueResultException` exception
Most commonly, more than 1 draft comment exists that were created milliseconds apart.
`jakarta.persistence.NonUniqueResultException: query did not return a unique result: 2`
This fix returns and updates only the latest draft comment and deletes the older draft comments.
Also, add a unit test

PIC-4022 BugFix: Return latest draft comment from list of draft comments

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingRepositoryFacade.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/OffenderEntityInitService.java
src/test/java/uk/gov/justice/probation/courtcaseservice/service/OffenderEntityInitServiceTest.java

1. Prevent null pointer exceptions by checking to see if the offender.defendants is null or not. This is because we use an optional offender.get() in order to hibernate.initialize / lazy load defendant data.
2. Add unit tests
Atm, we often see null pointer exceptions in the logs.
I believe that once the defendant / hearing is saved then the offender / defendant association will be fixed and you'll then be able to do offender.getDefendants() because a defendant actually then exists
⚠️ We have a seperate investigation to understand why offender.getDefendants is returning null instead of an empty list
My assumption is that we can have an Offender in the database coming from e.g. the pic_new_offender_events_queue .
That could lead to the defendant not existing in the table until the case / …

PIC-4138 Fix null pointer exception when trying to get offenders' defendants

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/repository/HearingRepositoryFacade.java

Remove logs that were used solely to debug a null pointer exception. It has been resolved so there's no longer a need for the logs.

PIC-4138 Remove logs after resolving bug

---

src/main/resources/db/migration/courtcase/V2182__rename_court_case_sequences.sql

Set the new_sequence to court_case_id_seq so that Hibernate can use it to set the id value during table insertions
Set the old_sequence from court_case_id_seq to court_case_old_id_seq which is no longer being used. (TODO: remove)
This should fix DataIntegrityViolationException issues we get which causes a lot of noise in our error logs
Error it resolves:
```
DataIntegrityViolationException
could not execute statement [ERROR: duplicate key value violates unique constraint "court_case_new_pkey"
Detail: Key (id)=(redacted) already exists.]
```
**Azure error:**
[Logs here](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%225055501c-7b54-11ef-ac1d-000d3a86bbe1%22,%22timestamp%22:%222024-09-25T15:38:55.362Z%22%7D/ComponentId/%7B%22Name%22:%22nomisap …

Alter sequence for court_case table

---

src/main/resources/db/migration/courtcase/V2185__add_index_hearing_defendant_table.sql

Add index to hearing defendant table on `fk_defendant_id`
One of the slowest and most CPU intensive queries is the one hibernate does to get all the hearing_defendants based on the defendant id. As in, the Defendant entity has many hearing defendants.
There's a similar query to get all hearing defendants using the fk_hearing_id which takes 8ms whilst the same one with fk_defendant_id takes 400ms. Hopefully the index should improve this
Adding an index to this should hopefully reduce the time it takes to retrieve this information and should improve performance on the PUT /hearing requests

Add index to hearing defendant table

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/DefendantEntity.java
src/main/resources/application.yml

Set store_data_at_delete to true.
**This fixes the issue below:**
`
org.postgresql.util.PSQLException: ERROR: null value in column "prep_status" of relation "hearing_defendant_aud" violates not-null constraint
`
When a record is deleted in the original table, the audit table does an insert with null values in the columns. However, there's a not null constraint on the prep_status column which causes an exception. This configuration should stop the need to add null values for a deltion.
- Also, remove unused imports

PIC-4372b Fix audit table issue in preprod

---

src/main/resources/db/migration/courtcase/V2190__remove_constaint_hearing_defendant_aud.sql

Remove `fk_hearing_defendant_hearing_outcome` constraint from the audit table.
This will allow for duplicate hearing_defendants to be removed and duplicate hearing outcomes.

PIC-4372b Remove-audit-table-constraint

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java

Lazy load the case defendants documents to fix the error:
> org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: uk.gov.justice.probation.courtcaseservice.jpa.entity.CaseDefendantEntity.documents: could not initialize proxy - no Session
...
> uk.gov.justice.probation.courtcaseservice.controller.mapper.CourtCaseResponseMapper.mapCaseDocuments(CourtCaseResponseMapper.java:51)

PIC-4509 Fix case document lazy loading

---

src/main/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseController.java
src/main/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapper.java
src/main/java/uk/gov/justice/probation/courtcaseservice/service/HearingEntityInitService.java
src/main/kotlin/uk/gov/justice/probation/courtcaseservice/service/ProbationCaseEngagementService.kt
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/CourtCaseControllerTest.java
src/test/java/uk/gov/justice/probation/courtcaseservice/controller/mapper/CourtCaseResponseMapperTest.java

Lazy load case documents
Turn courtCaseResponseMapper to a service class in order to use Transactional in order to use Hibernate.initialize.

BugFix: Lazy load case documents

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/healthchecks/NomisAuth.java
src/main/resources/application-dev.yml
src/main/resources/application-docker.yml
src/main/resources/application-local.yml
src/main/resources/application-wiremock.yml
src/main/resources/application.yml
src/test/resources/application-test.yml

Remove (undo)  `pinger.setPath("/auth/health/ping")` of the [previous related PR](https://github.com/ministryofjustice/court-case-service/pull/1338) which affects all classes using `Pinger` causing all those other api health checks to end with `/auth/health/ping`
Set the base path of `nomis-auth` to have `/auth` appended to it
Undo `nomis-auth` ping path

BugFix pinger calls to external apis

---

src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/DefendantProbationStatus.java
src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/OffenderProbationStatus.java
src/test/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/OffenderProbationStatusTest.java

Try mapping 'No Record' explicitly instead of in the exception, revert OffenderProbation changes

PIC-4566: Try mapping 'No Record' explicitly instead

---

src/main/resources/logback-spring.xml

Remove app insights appender from logback after upgrading app inisghts java agent to 3.x which means logback is autoinstrumented

PIC-4103 Remove app insights appender from logback

---

src/main/java/uk/gov/justice/probation/courtcaseservice/application/WebClientConfig.java

Increase to 50MB because our service allows for 50mb files to be uploaded to HMPPS Document API Service.

PIC-4640 allow downloading 50mb file max

---

Dockerfile

This contains less cve security vulnerabilities. (tested locally successfully)

PIC-4650 Use eclipse java image

---

src/main/resources/db/migration/courtcase/V2196__add_index_case_marker.sql

This should help speed up requests to the table on fk_court_case_id
Thus improving the overall performance of getting "court cases" as a whole as it has an association to it.
It's a Hibernate made query that in one request could accumulate to 100 milliseconds or so.
> SELECT case_marker
[example of logs in Azure](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%22484e0864-408c-11f0-be51-002248c5d09f%22,%22timestamp%22:%222025-06-03T15:06:01.889Z%22%7D/ComponentId/%7B%22Name%22:%22nomisapi-prod%22,%22ResourceGroup%22:%22nomisapi-prod-rg%22,%22SubscriptionId%22:%22a5ddf257-3b21-4ba9-a28c-ab30f751b383%22%7D)
[example 2](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactVie …

Add index to case_marker table
